alter table address_book drop foreign key FKFB8B054B41C0965;
alter table branch drop foreign key FKADAF25A2797DEFA1;
alter table branch drop foreign key FKADAF25A2DBC256B5;
alter table branch drop foreign key FKADAF25A2DF4B1732;
alter table cal_event drop foreign key FKABCCC2E94BF6E69A;
alter table calendar drop foreign key FKF55EFB3EB41C0965;
alter table commit_item drop foreign key FK5A19351B24564550;
alter table commit_item drop foreign key FK5A19351B5844BC56;
alter table commit_item drop foreign key FK5A19351B87B0AAE2;
alter table contact drop foreign key FK38B724209E879473;
alter table deleted_item drop foreign key FKEE892B79C498A977;
alter table deleted_item drop foreign key FKEE892B79D23A15E0;
alter table deleted_item drop foreign key FKEE892B796259B2DB;
alter table directory_member drop foreign key FK84B4C4AC128EE6EF;
alter table directory_member drop foreign key FK84B4C4AC288B1AFF;
alter table fanout_entry drop foreign key FKD6C6228E8E483F02;
alter table item_version drop foreign key FKC31F7BACA664A544;
alter table permission drop foreign key FKE125C5CFD928E814;
alter table permission drop foreign key FKE125C5CFBE7D0D6E;
alter table repository drop foreign key FK7446DB4A27CAD3C3;
alter table repository drop foreign key FK7446DB4ADBC256B5;
alter table share drop foreign key FK6854FDFF9ACA084;
alter table user_entity drop foreign key FKDED72AD7ADFB913D;
alter table volume_instance drop foreign key FK6A9A3C1ACBA82DD2;
drop table if exists address_book;
drop table if exists base_entity;
drop table if exists blob_hash;
drop table if exists branch;
drop table if exists cal_event;
drop table if exists calendar;
drop table if exists commit_item;
drop table if exists contact;
drop table if exists deleted_item;
drop table if exists directory_member;
drop table if exists fanout_entry;
drop table if exists fanout_hash;
drop table if exists item;
drop table if exists item_version;
drop table if exists permission;
drop table if exists repository;
drop table if exists share;
drop table if exists user_entity;
drop table if exists volume;
drop table if exists volume_instance;
create table address_book (id bigint not null auto_increment, name varchar(255) not null, description varchar(255), created_date date not null, modified_date date not null, owner varchar(255), primary key (id));
create table base_entity (name varchar(255) not null, created_date date not null, modified_date date not null, primary key (name));
create table blob_hash (blob_hash bigint not null, volume_id bigint not null, primary key (blob_hash));
create table branch (id bigint not null auto_increment, name varchar(255) not null, linked_to bigint, repository bigint not null, head bigint, primary key (id));
create table cal_event (id bigint not null auto_increment, name varchar(255) not null, description varchar(255), timezone varchar(255), created_date datetime not null, modified_date datetime not null, ctag bigint not null, start_date datetime not null, end_date datetime not null, summary varchar(255), calendar bigint not null, primary key (id));
create table calendar (id bigint not null auto_increment, name varchar(255) not null, created_date datetime not null, modified_date datetime not null, ctag bigint not null, color varchar(255), owner varchar(255) not null, primary key (id), unique (name, owner));
create table commit_item (id bigint not null auto_increment, created_date datetime, root_item_version bigint not null, editor varchar(255), branch bigint not null, primary key (id));
create table contact (id bigint not null auto_increment, name varchar(255) not null, created_date datetime not null, modified_date datetime not null, organization_name varchar(255), telephonenumber varchar(255), given_name varchar(255), sur_name varchar(255), mail varchar(255), uid varchar(255) not null, address_book bigint not null, primary key (id));
create table deleted_item (id bigint not null auto_increment, deleted_from bigint, deleted_resource bigint, repo_version bigint, primary key (id));
create table directory_member (id bigint not null auto_increment, name text, member_item bigint not null, parent_item bigint not null, primary key (id), unique (name, parent_item));
create table fanout_entry (id bigint not null auto_increment, chunk_hash bigint, fanout bigint, primary key (id));
create table fanout_hash (fanout_hash bigint not null, actual_content_length bigint not null, primary key (fanout_hash));
create table item (id bigint not null auto_increment, type varchar(1) not null, create_date date not null, primary key (id));
create table item_version (id bigint not null auto_increment, modified_date date not null, item_hash bigint not null, item bigint not null, primary key (id));
create table permission (id bigint not null auto_increment, priviledge integer, granted_on bigint, grantee varchar(255), primary key (id));
create table repository (id bigint not null auto_increment, name varchar(255), created_date date not null, base_entity varchar(255) not null, head bigint, primary key (id));
create table share (id tinyblob not null, created_date date not null, priviledge integer, share_recip varchar(255), accepted_date date, shared_from bigint not null, primary key (id));
create table user_entity (name varchar(255) not null, email varchar(255) not null, password varchar(255), primary key (name));
create table volume (id bigint not null auto_increment, target_capacity bigint not null, used_bytes bigint not null, primary key (id));
create table volume_instance (id bigint not null auto_increment, location varchar(255) not null, instance_type varchar(255) not null, capacity bigint, cost integer not null, online bit not null, lost bit not null, volume bigint, primary key (id), unique (location, instance_type));
alter table address_book add index FKFB8B054B41C0965 (owner), add constraint FKFB8B054B41C0965 foreign key (owner) references base_entity (name);
alter table branch add index FKADAF25A2797DEFA1 (linked_to), add constraint FKADAF25A2797DEFA1 foreign key (linked_to) references branch (id);
alter table branch add index FKADAF25A2DBC256B5 (head), add constraint FKADAF25A2DBC256B5 foreign key (head) references commit_item (id);
alter table branch add index FKADAF25A2DF4B1732 (repository), add constraint FKADAF25A2DF4B1732 foreign key (repository) references repository (id);
alter table cal_event add index FKABCCC2E94BF6E69A (calendar), add constraint FKABCCC2E94BF6E69A foreign key (calendar) references calendar (id);
alter table calendar add index FKF55EFB3EB41C0965 (owner), add constraint FKF55EFB3EB41C0965 foreign key (owner) references base_entity (name);
alter table commit_item add index FK5A19351B24564550 (root_item_version), add constraint FK5A19351B24564550 foreign key (root_item_version) references item_version (id);
alter table commit_item add index FK5A19351B5844BC56 (editor), add constraint FK5A19351B5844BC56 foreign key (editor) references user_entity (name);
alter table commit_item add index FK5A19351B87B0AAE2 (branch), add constraint FK5A19351B87B0AAE2 foreign key (branch) references branch (id);
alter table contact add index FK38B724209E879473 (address_book), add constraint FK38B724209E879473 foreign key (address_book) references address_book (id);
alter table deleted_item add index FKEE892B79C498A977 (deleted_from), add constraint FKEE892B79C498A977 foreign key (deleted_from) references item_version (id);
alter table deleted_item add index FKEE892B79D23A15E0 (repo_version), add constraint FKEE892B79D23A15E0 foreign key (repo_version) references commit_item (id);
alter table deleted_item add index FKEE892B796259B2DB (deleted_resource), add constraint FKEE892B796259B2DB foreign key (deleted_resource) references item_version (id);
alter table directory_member add index FK84B4C4AC128EE6EF (parent_item), add constraint FK84B4C4AC128EE6EF foreign key (parent_item) references item_version (id);
alter table directory_member add index FK84B4C4AC288B1AFF (member_item), add constraint FK84B4C4AC288B1AFF foreign key (member_item) references item_version (id);
alter table fanout_entry add index FKD6C6228E8E483F02 (fanout), add constraint FKD6C6228E8E483F02 foreign key (fanout) references fanout_hash (fanout_hash);
alter table item_version add index FKC31F7BACA664A544 (item), add constraint FKC31F7BACA664A544 foreign key (item) references item (id);
alter table permission add index FKE125C5CFD928E814 (granted_on), add constraint FKE125C5CFD928E814 foreign key (granted_on) references item (id);
alter table permission add index FKE125C5CFBE7D0D6E (grantee), add constraint FKE125C5CFBE7D0D6E foreign key (grantee) references base_entity (name);
alter table repository add index FK7446DB4A27CAD3C3 (base_entity), add constraint FK7446DB4A27CAD3C3 foreign key (base_entity) references base_entity (name);
alter table repository add index FK7446DB4ADBC256B5 (head), add constraint FK7446DB4ADBC256B5 foreign key (head) references commit_item (id);
alter table share add index FK6854FDFF9ACA084 (shared_from), add constraint FK6854FDFF9ACA084 foreign key (shared_from) references branch (id);
alter table user_entity add index FKDED72AD7ADFB913D (name), add constraint FKDED72AD7ADFB913D foreign key (name) references base_entity (name);
alter table volume_instance add index FK6A9A3C1ACBA82DD2 (volume), add constraint FK6A9A3C1ACBA82DD2 foreign key (volume) references volume (id);
