drop table address_book cascade constraints;
drop table base_entity cascade constraints;
drop table blob_hash cascade constraints;
drop table branch cascade constraints;
drop table cal_event cascade constraints;
drop table calendar cascade constraints;
drop table commit_item cascade constraints;
drop table contact cascade constraints;
drop table deleted_item cascade constraints;
drop table directory_member cascade constraints;
drop table fanout_entry cascade constraints;
drop table fanout_hash cascade constraints;
drop table item cascade constraints;
drop table item_version cascade constraints;
drop table permission cascade constraints;
drop table repository cascade constraints;
drop table share cascade constraints;
drop table user_entity cascade constraints;
drop table volume cascade constraints;
drop table volume_instance cascade constraints;
drop sequence hibernate_sequence;
create table address_book (id number(19,0) not null, name varchar2(255 char) not null, description varchar2(255 char), created_date date not null, modified_date date not null, owner varchar2(255 char), primary key (id));
create table base_entity (name varchar2(255 char) not null, created_date date not null, modified_date date not null, primary key (name));
create table blob_hash (blob_hash number(19,0) not null, volume_id number(19,0) not null, primary key (blob_hash));
create table branch (id number(19,0) not null, name varchar2(255 char) not null, repository number(19,0) not null, head number(19,0), linked_to number(19,0), primary key (id));
create table cal_event (id number(19,0) not null, name varchar2(255 char) not null, description varchar2(255 char), timezone varchar2(255 char), created_date timestamp not null, modified_date timestamp not null, ctag number(19,0) not null, start_date timestamp not null, end_date timestamp not null, summary varchar2(255 char), calendar number(19,0) not null, primary key (id));
create table calendar (id number(19,0) not null, name varchar2(255 char) not null, created_date timestamp not null, modified_date timestamp not null, ctag number(19,0) not null, color varchar2(255 char), owner varchar2(255 char) not null, primary key (id), unique (name, owner));
create table commit_item (id number(19,0) not null, created_date timestamp, root_item_version number(19,0) not null, editor varchar2(255 char), branch number(19,0) not null, primary key (id));
create table contact (id number(19,0) not null, name varchar2(255 char) not null, created_date timestamp not null, modified_date timestamp not null, organization_name varchar2(255 char), telephonenumber varchar2(255 char), given_name varchar2(255 char), sur_name varchar2(255 char), mail varchar2(255 char), uid varchar2(255 char) not null, address_book number(19,0) not null, primary key (id));
create table deleted_item (id number(19,0) not null, repo_version number(19,0), deleted_resource number(19,0), deleted_from number(19,0), primary key (id));
create table directory_member (id number(19,0) not null, name varchar2(1000 char), parent_item number(19,0) not null, member_item number(19,0) not null, primary key (id), unique (name, parent_item));
create table fanout_entry (id number(19,0) not null, chunk_hash number(19,0), fanout number(19,0), primary key (id));
create table fanout_hash (fanout_hash number(19,0) not null, actual_content_length number(19,0) not null, primary key (fanout_hash));
create table item (id number(19,0) not null, type varchar2(1 char) not null, create_date date not null, primary key (id));
create table item_version (id number(19,0) not null, modified_date date not null, item_hash number(19,0) not null, item number(19,0) not null, primary key (id));
create table permission (id number(19,0) not null, priviledge number(10,0), grantee varchar2(255 char), granted_on number(19,0), primary key (id));
create table repository (id number(19,0) not null, name varchar2(255 char), created_date date not null, base_entity varchar2(255 char) not null, head number(19,0), primary key (id));
create table share (id raw(255) not null, created_date date not null, priviledge number(10,0), share_recip varchar2(255 char), accepted_date date, shared_from number(19,0) not null, primary key (id));
create table user_entity (name varchar2(255 char) not null, email varchar2(255 char) not null, password varchar2(255 char), primary key (name));
create table volume (id number(19,0) not null, target_capacity number(19,0) not null, used_bytes number(19,0) not null, primary key (id));
create table volume_instance (id number(19,0) not null, location varchar2(255 char) not null, instance_type varchar2(255 char) not null, capacity number(19,0), cost number(10,0) not null, online number(1,0) not null, lost number(1,0) not null, volume number(19,0), primary key (id), unique (location, instance_type));
alter table address_book add constraint FKFB8B054B41C0965 foreign key (owner) references base_entity;
alter table branch add constraint FKADAF25A2797DEFA1 foreign key (linked_to) references branch;
alter table branch add constraint FKADAF25A2DBC256B5 foreign key (head) references commit_item;
alter table branch add constraint FKADAF25A2DF4B1732 foreign key (repository) references repository;
alter table cal_event add constraint FKABCCC2E94BF6E69A foreign key (calendar) references calendar;
alter table calendar add constraint FKF55EFB3EB41C0965 foreign key (owner) references base_entity;
alter table commit_item add constraint FK5A19351B24564550 foreign key (root_item_version) references item_version;
alter table commit_item add constraint FK5A19351B5844BC56 foreign key (editor) references user_entity;
alter table commit_item add constraint FK5A19351B87B0AAE2 foreign key (branch) references branch;
alter table contact add constraint FK38B724209E879473 foreign key (address_book) references address_book;
alter table deleted_item add constraint FKEE892B79C498A977 foreign key (deleted_from) references item_version;
alter table deleted_item add constraint FKEE892B79D23A15E0 foreign key (repo_version) references commit_item;
alter table deleted_item add constraint FKEE892B796259B2DB foreign key (deleted_resource) references item_version;
alter table directory_member add constraint FK84B4C4AC128EE6EF foreign key (parent_item) references item_version;
alter table directory_member add constraint FK84B4C4AC288B1AFF foreign key (member_item) references item_version;
alter table fanout_entry add constraint FKD6C6228E8E483F02 foreign key (fanout) references fanout_hash;
alter table item_version add constraint FKC31F7BACA664A544 foreign key (item) references item;
alter table permission add constraint FKE125C5CFD928E814 foreign key (granted_on) references item;
alter table permission add constraint FKE125C5CFBE7D0D6E foreign key (grantee) references base_entity;
alter table repository add constraint FK7446DB4A27CAD3C3 foreign key (base_entity) references base_entity;
alter table repository add constraint FK7446DB4ADBC256B5 foreign key (head) references commit_item;
alter table share add constraint FK6854FDFF9ACA084 foreign key (shared_from) references branch;
alter table user_entity add constraint FKDED72AD7ADFB913D foreign key (name) references base_entity;
alter table volume_instance add constraint FK6A9A3C1ACBA82DD2 foreign key (volume) references volume;
create sequence hibernate_sequence;
