alter table address_book drop constraint FKFB8B054B41C0965;
alter table branch drop constraint FKADAF25A2797DEFA1;
alter table branch drop constraint FKADAF25A2DBC256B5;
alter table branch drop constraint FKADAF25A2DF4B1732;
alter table cal_event drop constraint FKABCCC2E94BF6E69A;
alter table calendar drop constraint FKF55EFB3EB41C0965;
alter table commit_item drop constraint FK5A19351B24564550;
alter table commit_item drop constraint FK5A19351B5844BC56;
alter table commit_item drop constraint FK5A19351B87B0AAE2;
alter table contact drop constraint FK38B724209E879473;
alter table deleted_item drop constraint FKEE892B79C498A977;
alter table deleted_item drop constraint FKEE892B79D23A15E0;
alter table deleted_item drop constraint FKEE892B796259B2DB;
alter table directory_member drop constraint FK84B4C4AC128EE6EF;
alter table directory_member drop constraint FK84B4C4AC288B1AFF;
alter table fanout_entry drop constraint FKD6C6228E8E483F02;
alter table item_version drop constraint FKC31F7BACA664A544;
alter table permission drop constraint FKE125C5CFD928E814;
alter table permission drop constraint FKE125C5CFBE7D0D6E;
alter table repository drop constraint FK7446DB4A27CAD3C3;
alter table repository drop constraint FK7446DB4ADBC256B5;
alter table share drop constraint FK6854FDFF9ACA084;
alter table user_entity drop constraint FKDED72AD7ADFB913D;
alter table volume_instance drop constraint FK6A9A3C1ACBA82DD2;
drop table address_book;
drop table base_entity;
drop table blob_hash;
drop table branch;
drop table cal_event;
drop table calendar;
drop table commit_item;
drop table contact;
drop table deleted_item;
drop table directory_member;
drop table fanout_entry;
drop table fanout_hash;
drop table item;
drop table item_version;
drop table permission;
drop table repository;
drop table share;
drop table user_entity;
drop table volume;
drop table volume_instance;
drop sequence hibernate_sequence;
create table address_book (id int8 not null, name varchar(255) not null, description varchar(255), created_date date not null, modified_date date not null, owner varchar(255), primary key (id));
create table base_entity (name varchar(255) not null, created_date date not null, modified_date date not null, primary key (name));
create table blob_hash (blob_hash int8 not null, volume_id int8 not null, primary key (blob_hash));
create table branch (id int8 not null, name varchar(255) not null, head int8, repository int8 not null, linked_to int8, primary key (id));
create table cal_event (id int8 not null, name varchar(255) not null, description varchar(255), timezone varchar(255), created_date timestamp not null, modified_date timestamp not null, ctag int8 not null, start_date timestamp not null, end_date timestamp not null, summary varchar(255), calendar int8 not null, primary key (id));
create table calendar (id int8 not null, name varchar(255) not null, created_date timestamp not null, modified_date timestamp not null, ctag int8 not null, color varchar(255), owner varchar(255) not null, primary key (id), unique (name, owner));
create table commit_item (id int8 not null, created_date timestamp, editor varchar(255), branch int8 not null, root_item_version int8 not null, primary key (id));
create table contact (id int8 not null, name varchar(255) not null, created_date timestamp not null, modified_date timestamp not null, organization_name varchar(255), telephonenumber varchar(255), given_name varchar(255), sur_name varchar(255), mail varchar(255), uid varchar(255) not null, address_book int8 not null, primary key (id));
create table deleted_item (id int8 not null, repo_version int8, deleted_from int8, deleted_resource int8, primary key (id));
create table directory_member (id int8 not null, name varchar(1000), parent_item int8 not null, member_item int8 not null, primary key (id), unique (name, parent_item));
create table fanout_entry (id int8 not null, chunk_hash int8, fanout int8, primary key (id));
create table fanout_hash (fanout_hash int8 not null, actual_content_length int8 not null, primary key (fanout_hash));
create table item (id int8 not null, type varchar(1) not null, create_date date not null, primary key (id));
create table item_version (id int8 not null, modified_date date not null, item_hash int8 not null, item int8 not null, primary key (id));
create table permission (id int8 not null, priviledge int4, granted_on int8, grantee varchar(255), primary key (id));
create table repository (id int8 not null, name varchar(255), created_date date not null, head int8, base_entity varchar(255) not null, primary key (id));
create table share (id bytea not null, created_date date not null, priviledge int4, share_recip varchar(255), accepted_date date, shared_from int8 not null, primary key (id));
create table user_entity (name varchar(255) not null, email varchar(255) not null, password varchar(255), primary key (name));
create table volume (id int8 not null, target_capacity int8 not null, used_bytes int8 not null, primary key (id));
create table volume_instance (id int8 not null, location varchar(255) not null, instance_type varchar(255) not null, capacity int8, cost int4 not null, online bool not null, lost bool not null, volume int8, primary key (id), unique (location, instance_type));
alter table address_book add constraint FKFB8B054B41C0965 foreign key (owner) references base_entity;
alter table branch add constraint FKADAF25A2797DEFA1 foreign key (linked_to) references branch;
alter table branch add constraint FKADAF25A2DBC256B5 foreign key (head) references commit_item;
alter table branch add constraint FKADAF25A2DF4B1732 foreign key (repository) references repository;
alter table cal_event add constraint FKABCCC2E94BF6E69A foreign key (calendar) references calendar;
alter table calendar add constraint FKF55EFB3EB41C0965 foreign key (owner) references base_entity;
alter table commit_item add constraint FK5A19351B24564550 foreign key (root_item_version) references item_version;
alter table commit_item add constraint FK5A19351B5844BC56 foreign key (editor) references user_entity;
alter table commit_item add constraint FK5A19351B87B0AAE2 foreign key (branch) references branch;
alter table contact add constraint FK38B724209E879473 foreign key (address_book) references address_book;
alter table deleted_item add constraint FKEE892B79C498A977 foreign key (deleted_from) references item_version;
alter table deleted_item add constraint FKEE892B79D23A15E0 foreign key (repo_version) references commit_item;
alter table deleted_item add constraint FKEE892B796259B2DB foreign key (deleted_resource) references item_version;
alter table directory_member add constraint FK84B4C4AC128EE6EF foreign key (parent_item) references item_version;
alter table directory_member add constraint FK84B4C4AC288B1AFF foreign key (member_item) references item_version;
alter table fanout_entry add constraint FKD6C6228E8E483F02 foreign key (fanout) references fanout_hash;
alter table item_version add constraint FKC31F7BACA664A544 foreign key (item) references item;
alter table permission add constraint FKE125C5CFD928E814 foreign key (granted_on) references item;
alter table permission add constraint FKE125C5CFBE7D0D6E foreign key (grantee) references base_entity;
alter table repository add constraint FK7446DB4A27CAD3C3 foreign key (base_entity) references base_entity;
alter table repository add constraint FK7446DB4ADBC256B5 foreign key (head) references commit_item;
alter table share add constraint FK6854FDFF9ACA084 foreign key (shared_from) references branch;
alter table user_entity add constraint FKDED72AD7ADFB913D foreign key (name) references base_entity;
alter table volume_instance add constraint FK6A9A3C1ACBA82DD2 foreign key (volume) references volume;
create sequence hibernate_sequence;
